# Generated by Django 3.0.4 on 2020-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_db', models.TextField(default='NA')),
                ('password_db', models.TextField(default='NA')),
            ],
        ),
    ]
